-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 15:23:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eshop` DEFAULT CHARACTER SET utf8 ;
USE `eshop` ;

-- -----------------------------------------------------
-- Table `eshop`.`produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produkty` (
  id  INT NOT NULL,
  název VARCHAR(250) NOT NULL,
  popis TEXT(1000) NULL,
  cena DECIMAL(10,2) NOT NULL,
  obrázek VARCHAR(250) NULL,
  dostupnost INT NULL,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eshop`.`uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uzivatele` (
  id INT NOT NULL ,
  jméno VARCHAR(150) NOT NULL,
  email VARCHAR(250) NOT NULL,
  heslo VARCHAR(100) NOT NULL,
  adresa VARCHAR(150) NOT NULL,
  psc VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eshop`.`objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objednavka` (
  id INT NOT NULL,
  uzivatele_id_uzivatele INT NOT NULL,
  datum DATE NULL,
  stav ENUM('v procesu', 'odeslano') NULL,
  cena DECIMAL(10,2) NULL,
  PRIMARY KEY (id, uzivatele_id_uzivatele),
  FOREIGN KEY (uzivatele_id_uzivatele)
    REFERENCES uzivatele
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) 
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eshop`.`polozka objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polozka objednavky` (
  id INT NOT NULL,
  objednavka_id_objednavky INT NOT NULL,
  produkty_ID_produktu INT NOT NULL,
  pocet_kusu INT NULL,
  cena_za_polozku DECIMAL(10,2) NULL,
  PRIMARY KEY (id, objednavka_id_objednavky, produkty_ID_produktu),
  FOREIGN KEY (produkty_ID_produktu)
    REFERENCES produkty
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) 
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

